name: mundovirtual
description: Una nueva idea, mejorada y perfeccionada de lo que se conoce hoy como un directorio.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.1+1

environment:
  sdk: ">=2.13.4 <3.0.0"

dependencies:
  audioplayers: ^1.0.1
  barcode_image: ^2.0.1
  cached_network_image: ^3.2.1
  cloud_firestore: ^3.1.17
  cupertino_icons: ^1.0.4
  datetime_picker_formfield: ^2.0.0
  dotted_border: ^2.0.0+2
  easy_localization: ^3.0.2-dev
  firebase_auth: ^3.3.19
  firebase_core: ^1.17.1
  firebase_messaging: ^11.4.1
  firebase_storage: ^10.2.17
  flutter:
    sdk: flutter
  flutter_datetime_picker: ^1.5.1
  flutter_facebook_auth: null
  flutter_facebook_keyhash: ^0.0.4
  flutter_native_image: ^0.0.6+1
  flutter_sound: ^8.3.9
  font_awesome_flutter: ^10.1.0
  geocoding: ^2.0.1
  geoflutterfire: ^3.0.3
  geolocator: ^7.7.1
  google_maps_flutter: ^2.1.6
  image: ^3.2.0
  image_gallery_saver: ^1.7.1
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  intl_phone_number_input: ^0.7.0+2
  location: ^4.3.0
  map_picker: ^0.0.3
  multi_select_flutter: ^4.1.2
  multiselect: ^0.0.4
  numberpicker: ^2.1.1
  path_provider: ^2.0.10
  photo_view: ^0.14.0
  pin_code_fields: ^7.4.0
  permission_handler: ^6.0.1+1
  progress_dialog:
  random_string: ^2.3.1
  shared_preferences: ^2.0.15
  smooth_page_indicator: ^1.0.0+2
  soundpool: ^2.3.0
  sticky_headers: ^0.3.0+2
  the_apple_sign_in: ^1.1.1
  video_compress: ^3.1.0
  video_player: ^2.4.2
  video_thumbnail: ^0.5.0
  esc_pos_utils:
  bluetooth_thermal_printer:

dev_dependencies:
  flutter_launcher_icons: ^0.9.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/ic_launcher-playstore.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/flags/
    - assets/translations/
    - assets/audio/
    - assets/fonts/

  fonts:
    - family: Poppinsb
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

    - family: Poppinsl
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf

    - family: Poppinsm
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

    - family: Poppinsr
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: Poppinssb
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
